sayangdiptochakraborty.ipynb
Hello MLCC, I have solved assignment 2. All solutions present in sayangdiptochakraborty.ipynb file..
=> Sayangdiptochakraborty

Anubhavkumar45.ipynb
Was not able to do the sorting part
=> Assignment2 Solved

Debjit08.ipynb, Debjit08_Numpy_Examples_1.ipynb, Numpy_Exercises.ipynb
hey there ,,, I've solved the list problems please check these out..
=> list problem solved

anjali-001.ipynb
Check out the problem that I have solved!
=> Problem Solved!!

Copy_of_Numpy_Examples_1.ipynb, Numpy_Exercises.ipynb, lakshya1604.ipynb
=> Assignment 2 

Lists.ipynb, Numpy_Examples_1.ipynb, Numpy_Exercises.ipynb
=> Problem solved(List)

Assignment2.ipynb, Assignment_2_list_manipulation.ipynb, VedSengupta.ipynb
Assignment 2 List manipulation.
=> Ved sengupta

Zaurezzh.ipynb
I have solved the problem.
Check it out
=> Problem Solved

avishekdas128.ipynb
I have solved the Assignment-2! Check!
=> Problem Solved!

Lists.ipynb, Numpy_Examples_1.ipynb, Numpy_Exercises.ipynb
=> Subhrajyoti Dasgupta

cherry-rd.ipynb
Hey there MLCC guys!
I have completed assignment 2. Please check it out!
=> Assignment 2 -  Solved

swapnil-sh.ipynb
Hey, there MLCC!
I have completed the Assignment-2!
Kindly Check it out!
=> Assignment 2 Full Completed !

gopal-agarwal.ipynb
Hey !!! Please check out my submission for Assignment 2!!!
=> Assignment 2 Solved!!!

joardar-aditya.ipynb
Hey, MLCC ! I have Solved Assignment 2
=> Assignment 2 Solved

Numpy_Examples_1.ipynb, Numpy_Exercises.ipynb, executable16.ipynb
Hey there MLCC guys please merge my pull request!!
=> Executable16

Lists.ipynb, Numpy_Examples_1.ipynb, Numpy_Exercises.ipynb
=> Ag creates

bitan2988.ipynb
hey guys i have completed my assignment plzzzzz give it a check
=> Assignment done

LIST__AhamedMohammedHussain.ipynb, NumpyExercises__AhamedMohammedHussain.ipynb
Assignment 2 Solved....Pls check it out...Give me any suggestions if any...(this is my first ML assignment)
=> Ahamed mohammed hussain

Lists.ipynb, Numpy_Examples_1.ipynb, Numpy_Exercises.ipynb, SoumanPaul.ipynb
Hi, MLCCKolkata !. I've completed Assignment2. check it out and marge it ASAP. 
Thank you.
=> Souman paul

Untitled3.ipynb
Hey...mlcc guys....i have completed the assignment...
plz check it out....
=> problem solved!!!

Numpy_Examples_1.ipynb, Numpy_Exercises.ipynb, rahul-1903.ipynb
I have assignment completed the assignment. Please verify it. Thank you.
=> Assignment 2

Lists.ipynb, Numpy_Examples_1.ipynb, Numpy_Exercises.ipynb
HEY MLCC Kolkata!  I Have completed my Assignment 2. Please check it out.
=> Nehasinghh

Untitled0.ipynb
Hey MLCC guys i have solved my Assignment 2 ,Please check it Out.
=> Susovan1612
